docs: readme
Galxe/grevm pull request #43
Opened 2024-12-27 07:07 UTC by Radovenchyk

Changed the link to the developer, the previous one didn't work

2025-02-13 04:20 UTC, nekomoto911 approved these changes

2025-02-17 12:39 UTC, octavio12345300 approved these changes
list

2025-02-17 12:41 UTC, octavio12345300 approved these changes
list

2025-02-17 13:04 UTC, octavio12345300 requested changes
list

2025-02-17 16:17 UTC, Radovenchyk commented
sorry, I didn't understand which list

2025-02-25 02:57 UTC, closed without merging